apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: bun-playground
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: bun-playground
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tempo
  ports:
    - name: http
      port: 3200
      targetPort: 3200
      protocol: TCP
    - name: otlp
      port: 4317
      targetPort: 4317
      protocol: TCP
