apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: bun-playground
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: bun-playground
data:
  SERVICE_NAME: user-service
  PORT: "3001"
  NODE_ENV: production
  LOG_LEVEL: info
  KAFKA_BROKERS: "kafka:9092"
  REDIS_URL: "redis://:changeme@redis:6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
